#!/bin/bash

ARCH=skylake   #we want avx/avx2 - if change, check fftw configure options

# this works for amazon linux 2 ami (amzn2-vmware_esx-2.0.20190313-x86_64.xfs.gpt.ova)
#   installs gcc/gfortran 7.3.1 20180303 (Red Hat 7.3.1-5)

p="${PWD}/local/octave" && [ -n "$1" ] && p="$1"

set -e

function get_tarball {
	if [ ! -e $(basename "$1") ];then curl -L "$1" > $(basename "$1"); fi
}

function mk_glpk {
	z="$1" && cd "$o" && get_tarball "https://ftp.gnu.org/gnu/glpk/${z}" && \
		j=$(echo $z|sed "s/.tar.gz//"|sed "s/.tgz//"|sed "s/.tar.bz2//") && tar -xvf $z && cd $j && \
		./configure --prefix=${p} --enable-shared CFLAGS="-O2 -mtune=${ARCH}" | tee ../glpk.log && \
		make -j4 | tee -a ../glpk.log && make -j4 check | tee -a ../glpk.log && \
		make install | tee -a ../glpk.log && cd .. && rm -rf ${j}*
}

function mk_fftw {
	z="$1" && cd "$o" && get_tarball "http://www.fftw.org/${z}" && \
		j=$(echo $z|sed "s/.tar.gz//"|sed "s/.tgz//"|sed "s/.tar.bz2//") && tar -xvf $z && cd $j && \
		OPT="--enable-sse2 --enable-avx --enable-avx2 --enable-shared=yes" && \
		./configure --prefix=${p} ${OPT} F77=gfortran CC=gcc | tee ../fftw.log && make -j4 | tee -a ../fftw.log && \
		make -j4 check | tee -a ../fftw.log && make install | tee -a ../fftw.log && make distclean && \
		OPT+="--enable-single --enable-sse" && \
		./configure --prefix=${p} ${OPT} F77=gfortran CC=gcc | tee -a ../fftw.log && make -j4 | tee -a ../fftw.log && \
		make -j4 check | tee -a ../fftw.log && make install | tee -a ../fftw.log && cd .. && rm -rf ${j}*
}

function mk_lapack {
	z="$1" && cd "$o" && get_tarball "http://www.netlib.org/lapack/${z}" && ou=$(ulimit -s) && ulimit -s unlimited && \
		sed "s/skylake/${ARCH}/g" patch.lapack > patch.lapack.${ARCH} && \
		j=$(echo $z|sed "s/.tar.gz//"|sed "s/.tgz//"|sed "s/.tar.bz2//") && \
		tar -xvf $z && patch -p0 -fNu < patch.lapack.${ARCH} && cd $j && make -j4 | tee ../lapack.log && \
		mv liblapack.* libblas.* ${p}/lib && cd .. && rm -rf ${j}* && ulimit -s ${ou}
}

function mk_octave_510 {   #but there's something wrong since hesnr.m crashes w/ a free statement. ugh
        z="$1" && cd "$o" && get_tarball "https://ftp.gnu.org/gnu/octave/${z}" && \
                j=$(echo $z|sed "s/.tar.gz//"|sed "s/.tgz//"|sed "s/.tar.bz2//") && \
                tar -xvf $z && cd $j && \
                ./configure --prefix=${p}  --disable-atomic-refcount --disable-rpath --disable-java \
                --with-glpk-includedir=${p}/include --with-glpk-libdir=${p}/lib --without-portaudio \
                --disable-docs --with-blas=${p}/lib/libblas.a --with-lapack=${p}/lib/liblapack.a --with-fftw3f-includedir=${p}/include \
                --with-fftw3f-libdir=${p}/lib --with-fftw3-includedir=${p}/include --with-fftw3-libdir=${p}/lib --without-arpack \
                --without-suitesparseconfig --without-sundials_nvecserial --without-sundials_ida --without-hdf5 --without-sndfile \
                --without-qhull --without-umfpack --without-cxsparse --without-cholmod --without-colamd --without-ccolamd --without-camd \
                --without-amd --without-qt --without-qrupdate --without-fltk  --without-opengl --without-bz2 --without-qscintilla --without-klu \
                CC=gcc CFLAGS="-O2 -mtune=${ARCH} -fPIC -DM_PI=3.1415926535897932384" \
                CXX=g++ CXXFLAGS="-g -O2 -mtune=${ARCH}" \
                F77=gfortran FFLAGS="-O2 -mtune=${ARCH} -fPIC" \
                CPPFLAGS="-I${p}/include" LDFLAGS="-L${p}/lib" | tee ../octave.log && \
                make -j4 | tee -a ../octave.log && make check | tee -a ../octave.log && make install | tee -a ../octave.log && cd .. && rm -rf ${j}*

}
function mk_octave {
	z="$1" && cd "$o" && get_tarball "https://ftp.gnu.org/gnu/octave/${z}" && \
		j=$(echo $z|sed "s/.tar.gz//"|sed "s/.tgz//"|sed "s/.tar.bz2//") && \
		tar -xvf $z && cd $j && \
		./configure --prefix=${p} --disable-java --with-glpk-includedir=${p}/include --with-glpk-libdir=${p}/lib \
		--disable-docs --with-blas=${p}/lib/libblas.a --with-lapack=${p}/lib/liblapack.a --with-fftw3f-includedir=${p}/include \
		--with-fftw3f-libdir=${p}/lib --with-fftw3-includedir=${p}/include --with-fftw3-libdir=${p}/lib --without-arpack \
		--without-umfpack --without-cxsparse --without-cholmod --without-colamd --without-ccolamd --without-cholmod --without-camd \
		--without-amd --without-OSMesa --without-qt --without-qrupdate --without-fltk  --without-opengl --without-bz2 \
		--without-hdf5 --without-sndfile --without-portaudio --disable-rpath \
		CC=gcc CFLAGS="-O2 -mtune=${ARCH} -fPIC -DM_PI=3.1415926535897932384" \
		CXX=g++ CXXFLAGS="-g -O2 -mtune=${ARCH}" \
		F77=gfortran FFLAGS="-O2 -mtune=${ARCH} -fPIC" \
		CPPFLAGS="-I${p}/include" LDFLAGS="-L${p}/lib" | tee ../octave.log && \
		make -j4 | tee -a ../octave.log && make check | tee -a ../octave.log && make install | tee -a ../octave.log && cd .. && rm -rf ${j}*
}

o=${PWD}
mkdir -p "${p}/lib"
export LD_LIBRARY_PATH=${p}/lib:$LD_LIBRARY_PATH  #otherwise it doesn't find ncurses library, sigh

mk_glpk "glpk-4.65.tar.gz" && mk_fftw "fftw-3.3.8.tar.gz" && mk_lapack "lapack-3.8.0.tar.gz" && mk_octave "octave-4.2.2.tar.gz" # "octave-5.1.0.tar.gz"
